In [1]:
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
import os, sys # For filepaths
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.feature_selection import VarianceThreshold
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.linear_model import LogisticRegression as LR
from sklearn.model_selection import GroupKFold, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import label_binarize
import pickle
import sklearn.preprocessing as pre



In [2]:
''' Add the datasets and libraries to the system path '''

# Find the path to our implementations
current_directory = os.getcwd()
parent_directory = os.path.dirname(current_directory)
home_directory = os.path.dirname(parent_directory)
libraries_path = os.path.join(home_directory, 'Libraries')

# Find the path to the datasets
datasets_path = os.path.join(home_directory, 'Datasets')

# Add them both to the system path
sys.path.append(datasets_path)
sys.path.append(libraries_path)

In [3]:
''' Load the dataset '''

dataset = np.load(os.path.join(datasets_path, 'fashion_train.npy'))
print("Dataset shape: ", dataset.shape)

Dataset shape:  (10000, 785)


In [4]:
X = dataset[:, :-1]  # Define the images as all columns except the last one
y = dataset[:, -1] # Define the labels as the last column

In [5]:
print(type(X))
print("X shape: ", X.shape)
print(type(y))
print("y shape: ", y.shape)

<class 'numpy.ndarray'>
X shape:  (10000, 784)
<class 'numpy.ndarray'>
y shape:  (10000,)


## Cross validation

In [6]:
# scaling the images
scaler = pre.StandardScaler()
X = scaler.fit_transform(X)

In [7]:
# import classifiers 
from sklearn import svm 
from CNN import CNN
from Bayes import Bayes_classifier
from sklearn.neighbors import KNeighborsClassifier as KNN

In [40]:
def accuracy(predictions, y_val): 
    correct_predictions = 0
    
    for yt, yp in zip(y_val, predictions):
        if yt == yp:
            correct_predictions += 1
    return correct_predictions/predictions.shape[0]


# SVM cross validation

In [41]:
np.mean(cross_val_score(svm.SVC(C=10), X, y, cv=5, scoring = 'accuracy'))

0.8633

In [42]:
np.mean(cross_val_score(svm.SVC(C=10), X, y, cv=5, scoring = 'precision_macro'))

0.8638848172810455

In [43]:
np.mean(cross_val_score(svm.SVC(C=10), X, y, cv=5, scoring = 'f1_macro'))

0.8634444008462324

In [44]:
np.mean(cross_val_score(svm.SVC(C=10), X, y, cv=5, scoring = 'recall_macro'))

0.8640947070385945

# CNN cross validation

In [8]:
np.mean(cross_val_score(CNN(), X, y, cv=5, scoring = 'accuracy'))

0.8552

In [ ]:
np.mean(cross_val_score(CNN(), X, y, cv=5, scoring = 'precision_macro'))

In [ ]:
np.mean(cross_val_score(CNN(), X, y, cv=5, scoring = 'f1_macro'))

In [ ]:
np.mean(cross_val_score(CNN(), X, y, cv=5, scoring = 'recall_macro'))

# Bayes cross validation

In [9]:
np.mean(cross_val_score(Bayes_classifier(0.5), X, y, cv=5, scoring = 'accuracy'))

(2000, 2)


c:\ITU\Machine_learning\ML_Project\Libraries\Bayes.py:61: RuntimeWarning: invalid value encountered in scalar divide
  denom = sum(np.multiply(self.class_priors(),self.pdf(test_x)))


(2000, 2)


c:\ITU\Machine_learning\ML_Project\Libraries\Bayes.py:61: RuntimeWarning: invalid value encountered in scalar divide
  denom = sum(np.multiply(self.class_priors(),self.pdf(test_x)))


(2000, 2)
(2000, 2)
(2000, 2)


0.6952999999999999

In [8]:
# Define classifiers
classifiers = [Bayes_classifier(3)]
classifier_names = ["Bayes"]
num_classifiers = len(classifiers)
num_folds = 5

group_kfold = KFold(n_splits=num_folds)

# Define functions to avoid code repetition
def get_metrics(classifiers, x, y):
    acc_val = np.empty([num_folds, num_classifiers])
    f1_val = np.empty([num_folds, num_classifiers])
    precision = np.empty([num_folds, num_classifiers])
    recall = np.empty([num_folds, num_classifiers])
    # roc_auc = np.empty([num_folds, num_classifiers])
    for i, (train_index, val_index) in enumerate(group_kfold.split(x, y)):
        x_train, x_val = x[train_index, :], x[val_index, :]
        y_train, y_val = y[train_index], y[val_index]
        print(x_val.shape)
        for j, clf in enumerate(classifiers):
            print(f"Classifier {j+1} - {classifier_names[j]}")
            clf.fit(x_train, y_train)
            predictions = clf.predict(x_val)
            acc_val[i, j] = accuracy_score(y_val, predictions)
            f1_val[i, j] = f1_score(y_val, predictions, average='micro')
            precision[i, j] = precision_score(y_val, predictions, zero_division=0, average='micro')
            recall[i, j] = recall_score(y_val, predictions, average='micro')
    print_metrics(acc_val, f1_val, precision, recall)
    return x_train, y_train, x_val, y_val

def print_metrics(acc_val, f1_val, precision, recall):
    average_acc = np.mean(acc_val, axis=0)
    average_f1 = np.mean(f1_val, axis=0)
    average_precision = np.mean(precision, axis=0)
    average_recall = np.mean(recall, axis=0)
    for i, classifier_name in enumerate(classifier_names):
        print(f"############ Classifier {i+1} - {classifier_name}:")
        print(f'Average F1 score = {average_f1[i]:.3f}')
        print(f'Average Accuracy = {average_acc[i]:.3f}')
        print(f'Average Precision = {average_precision[i]:.3f}')
        print(f'Average Recall = {average_recall[i]:.3f}')

get_metrics(classifiers, X,y)

(2000, 784)
Classifier 1 - Bayes
(2000, 2)
(2000, 784)
Classifier 1 - Bayes
(2000, 2)
(2000, 784)
Classifier 1 - Bayes
(2000, 2)
(2000, 784)
Classifier 1 - Bayes
(2000, 2)
(2000, 784)
Classifier 1 - Bayes
(2000, 2)
############ Classifier 1 - Bayes:
Average F1 score = 0.228
Average Accuracy = 0.228
Average Precision = 0.228
Average Recall = 0.228


(array([[-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        ...,
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531]]),
 array([0, 1, 0, ..., 4, 3, 1], dtype=uint8),
 array([[-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        [-0.0148165 , -0.03760239, -0.06245122, ..., -0.14119802,
         -0.06592056, -0.02908531],
        ...,
        

In [ ]:
# Normal feature selection
print("Running without feature selection")
x_train, y_train, x_val, y_val = get_metrics(classifiers, x, y, patient_id)

# Feature selection with variance threshold
print("Running with variance threshold feature selection")
threshold_value = 0.1
selector = VarianceThreshold(threshold=threshold_value)
x_selected = selector.fit_transform(x)
get_metrics(classifiers, x_selected, y, patient_id, "With variance threshold")

# Feature selection with PCA
print("Running with PCA feature selection")
pca_transformer = PCA(n_components=5)
x_pca = pca_transformer.fit_transform(x)
get_metrics(classifiers, x_pca, y, patient_id, "With PCA")

# Define the path where to save the file
pickle_path = 'Project-2_github_repo/Fixed/PROJECT/fyp2023/model_group02'

# Chosen classifier
classifier = KNN(n_neighbors=5)
classifier = classifier.fit(x, y)
filename = 'group02_classifier.sav'

# Check if the path exists, if not, create it
if not os.path.exists(pickle_path):
    os.makedirs(pickle_path)

pickle.dump(classifier, open(os.path.join(pickle_path, filename), 'wb'))


# Plot ROC curve for best classifier
clf = classifier
clf.fit(x_train, y_train)
y_score = clf.predict_proba(x_val)
fpr, tpr, _ = roc_curve(y_val, y_score[:, 1])
roc_auc = auc(fpr, tpr)
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title("Receiver Operating Characteristic")
plt.legend(loc="lower right")
plt.show()