In [1]:
''' Needed libraries '''

import numpy as np # For matrix operations and numerical processing
import os, sys # For filepaths

In [2]:
''' Add the datasets and libraries to the system path '''

# Find the path to our implementations
current_directory = os.getcwd()
parent_directory = os.path.dirname(current_directory)
home_directory = os.path.dirname(parent_directory)
libraries_path = os.path.join(home_directory, 'Libraries')

# Find the path to the datasets
datasets_path = os.path.join(home_directory, 'Datasets')

# Add them both to the system path
sys.path.append(datasets_path)
sys.path.append(libraries_path)

In [3]:
''' Loading in the dataset and splitting into observations and labels '''

dataset= np.load(os.path.join(datasets_path, 'fashion_train.npy'))  # Load dataset
X = dataset[:, :-1] # Define X as all columns except the last one
y = dataset[:, -1] # Define y as the last column
projection_matrix = np.load(os.path.join(f"{home_directory}/Exported_Data", 'LDA_projection.npy')) # Import projection_matrix from file

In [4]:
'''Import our Bayes classifier'''
from Bayes import Bayes_classifier

# Naive Bayes classifier

Naive Bayes classifier classifies to the class with the highest posterior probablity: 
$$ P(Y=k|x)=\frac{\pi_kf_k(x)}{\sum\limits_{l=1}^K\pi_kf_l(x)}$$

We estimate the class priors, $\pi_k$ using the proportion of training observations in class k $$\pi_k=\frac{\text{n. of observations in class k}}{\text{total n. of observations}}$$

We estimate the class priors, $\pi_k$ using the proportion of training observations in class k $$\pi_k=\frac{\text{n. of observations in class k}}{\text{total n. of observations}}$$

We estimate each density function $f_k(x_i)$ of a feature $x_i$ in each class $k$ using the Gaussian kernel density estimate
The Gaussian Kernel is given as below: $$K(x) = \frac{1}{\sigma \sqrt{2\pi}}e^{{-\frac{1}{2}\frac{(x-\mu)^2}{\sigma^2}}}$$

# Testing our implementation of Bayes 

In [5]:
h  = 1.06 * np.std(X) * np.power(X.shape[0], -1/5)
bc = Bayes_classifier(h)
bc.fit(X,y)

In [7]:
bc.class_priors()

[0.2033, 0.1947, 0.2001, 0.2005, 0.2014]

Chossing a datapoint, feature and class to compute the results for - to then compare to manual computation 

In [17]:
datapoint_feature = projection_matrix[100]
test_observation_feature = [-0.12, -0.23]

In [19]:
bc.kernel(datapoint_feature[1],test_observation_feature[1] )

0.026385329989916287

In [20]:
bc.kde(test_observation_feature)

[array([0.00173127, 0.00173751]),
 array([0.00126537, 0.00173264]),
 array([0.00172703, 0.00166856]),
 array([0.00173371, 0.00167777]),
 array([0.00172424, 0.00172092])]

In [21]:
bc.pdf(test_observation_feature)

[3.00811163637404e-06,
 2.192434162687451e-06,
 2.8816508438964213e-06,
 2.908760815837642e-06,
 2.967275949119978e-06]

In [22]:
bc.posterior_prob(test_observation_feature)

[0.21873456525452684,
 0.15267875194016584,
 0.20624077685256045,
 0.208597201213748,
 0.21374870473899896]

In [23]:
bc.classification(test_observation_feature) 

0